Repository Internet2-WG/rust-internet2, pull requests merged in 2022-06, with the labels that each got.

#23 Address typesystem refactoring
  .github/workflows/build.yml
  .github/workflows/codecov.yml
  .github/workflows/lint.yml
  .github/workflows/pre-publish.yml
  .github/workflows/publication.yml
  .github/workflows/test.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  Cargo.lock
  Cargo.toml
  addr/Cargo.toml
  addr/src/encoding.rs
  addr/src/inet.rs
  addr/src/lib.rs
  addr/src/node.rs
  addr/src/server.rs
  derive/Cargo.toml
  derive/examples/peer_api.rs
  derive/src/api.rs
  rust-toolchain.toml
  src/lib.rs
  src/presentation/sphinx.rs
  src/presentation/tlv.rs
  src/session/init.rs
  src/session/local_node.rs
  src/session/mod.rs
  src/session/node_addr.rs
  src/session/noise/handshake.rs
  src/session/noise/mod.rs
  src/session/noise/transcoder.rs
  src/session/session.rs
  src/transport/connect.rs
  src/transport/encrypted.rs
  src/transport/mod.rs
  src/transport/socket_addr.rs
  src/transport/unencrypted.rs
  src/transport/websocket.rs
  src/transport/zeromq.rs
  tests/noise_xk.rs
  tests/zmq.rs
Labels: epic, refactoring

#24 Upgrade to zmq2 library
  .github/workflows/build.yml
  .github/workflows/codecov.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
Labels: upstream, refactoring

#26 Rm local session frame size checks
  src/session/transcoders.rs
  src/transport/mod.rs
  src/transport/zeromq.rs
  tests/zmq.rs
Labels: bug, *compatibility*, *scalability*, *consensus*
